[package]
name = "wgpu-vello"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bytemuck = { version = "1.23.0", features = ["derive"] }
cgmath = "0.18.0"
env_logger = "0.11.8"
log = "0.4.27"
pollster = "0.4.0"
vello = "0.5.0"
wgpu = "24.0.0"
winit = "0.30.9"
